### ISSUE TITLE
Can't click on eye icon to view my password during sign up

### ISSUE THREAD

**Issue by JaneQuichocho** [Pug-Life-INFO-461/allowance-gamification-app#168] opened 2018-06-04 05:38 UTC
Reproduction steps
1. Go to sign up
2. Type in password
3. Click on eye icon that appears to the right when you type in your password

I think I should be able to see my password but nothing happens and the icon disappears.

**Comment by 5tigerjelly** [comment] 2018-06-04 16:52
Duplicate of #165

**Closed** 2018-06-05 01:39 UTC
Labels: Duplicate

**Comment by JourneyToTheWes** [comment] 2018-06-05 21:00
Revealing password by the icon is not in requirements, the icon was originally just a stylistic touch. Viewing password now works though.
