### ISSUE TITLE
uncaught error reference.update failed

### ISSUE THREAD

**Issue by harrybarng** [Pug-Life-INFO-461/allowance-gamification-app#180] opened 2018-06-04 08:43 UTC
![image](https://user-images.githubusercontent.com/37923379/40907389-88e3c278-6798-11e8-8fa3-167607b4d6ab.png)
Same family same task, tried to accept as a child but does not let do so

**Comment by 5tigerjelly** [comment] 2018-06-04 16:54
Duplicate of #163

**Closed** 2018-06-05 01:39 UTC
Labels: Duplicate
